version: '3.7'
services:
  server:
    image: nginx
    restart: always
    environment:
      - 'APP_URL=http://in.localhost:8081'
    volumes:
      - 'nginx_config:/etc/nginx/conf.d:ro'
      - 'public_data:/var/www/app/public:ro'
    depends_on:
      - app
    ports:
      - '8081:80'
    networks:
      - invoiceninja
  app:
    image: 'invoiceninja/invoiceninja:5'
    environment:
      - APP_DEBUG=true
      - APP_KEY=gyKTjSDudh8SM0+i7dMAqtADAON+o8tQREEP4Bfp95E=
      - 'APP_URL=http://in.localhost:8081'
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - IN_PASSWORD=
      - IN_USER_EMAIL=
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=user@example.com
      - 'MAIL_FROM_NAME=Self Hosted User'
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_MAILER=log
      - MAIL_PASSWORD=null
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MYSQL_DATABASE=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - NORDIGEN_SECRET_ID=
      - NORDIGEN_SECRET_KEY=
      - PDF_GENERATOR=snappdf
      - PHANTOMJS_PDF_GENERATION=false
      - QUEUE_CONNECTION=database
      - REQUIRE_HTTPS=false
      - 'TRUSTED_PROXIES=*'
    restart: always
    volumes:
      - 'public_data:/var/www/app/public:rw,delegated'
      - 'storage_data:/var/www/app/storage:rw,delegated'
      - 'php_config:/usr/local/etc/php:rw'
    depends_on:
      - db
    networks:
      - invoiceninja
  db:
    image: 'mariadb:10.5'
    ports:
      - '3305:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_DATABASE=ninja
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
    volumes:
      - 'db_data:/var/lib/mysql:rw,delegated'
    networks:
      - invoiceninja
networks:
  invoiceninja: null
volumes:
  nginx_config: null
  public_data: null
  storage_data: null
  php_config: null
  db_data: null
labels:
  - coolify.managed=true
  - coolify.applicationId=5
  - coolify.type=application
  - traefik.enable=true
  - 'traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)'
  - traefik.http.routers.<unique_router_name>.entryPoints=http
