version: '3.7'

services:
  app:
    image: invoiceninja/invoiceninja:5
    command: >
      sh -c "chmod 755 /var/www/app/public && chown -R 1500:1500 /var/www/app && php-fpm"
    environment:
      - APP_DEBUG=true
      - APP_KEY=gyKTjSDudh8SM0+i7dMAqtADAON+o8tQREEP4Bfp95E=
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - IN_PASSWORD=
      - IN_USER_EMAIL=
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=user@example.com
      - MAIL_FROM_NAME=Self Hosted User
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_MAILER=log
      - MAIL_PASSWORD=null
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MYSQL_DATABASE=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_USER=ninja
      - NORDIGEN_SECRET_ID=
      - NORDIGEN_SECRET_KEY=
      - PDF_GENERATOR=snappdf
      - PHANTOMJS_PDF_GENERATION=false
      - QUEUE_CONNECTION=database
      - REQUIRE_HTTPS=false
      - TRUSTED_PROXIES=*
    restart: always
    ports:
      - "8000:9000" # Expose the app on port 8000
    volumes:
      - public_data:/var/www/app/public:rw,delegated
      - storage_data:/var/www/app/storage:rw,delegated
      - php_config:/usr/local/etc/php:rw
    depends_on:
      - db
    networks:
      - invoiceninja

  db:
    image: mariadb:10.5
    ports:
      - "3305:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ninjaAdm1nPassword
      - MYSQL_DATABASE=ninja
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
    volumes:
      - db_data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

networks:
  invoiceninja:

volumes:
  public_data:
  storage_data:
  php_config:
  db_data:
